### ISSUE TITLE
input[type="search"] ga margin-right berish kerak.

### ISSUE THREAD

**Issue by akramjonnuriddinov** [MIRZOULUGBEK9008/countries-selfmade#1]
![image](https://user-images.githubusercontent.com/99048411/163146987-4ddb46c5-8e3a-496f-b545-d14a3af2ccfb.png)
Shu joyda margin right berib qo'yilmasa ekram kichiklashganda input va select bir-biriga yopishib qolyapti.

**Comment by MIRZOULUGBEK9008** [comment]
#fix
